spec:
  template:
    spec:
      containers:
        - name: vertx-microservice
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace